title: <p align="center"> Mohit Paliwal </p>
logo: /assets/img/IMG_20190706_094506.jpg
description: I am working as a Applied ML engineer currently in IDP domain.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
